- name: loading platform variables
  include_vars: "{{ ansible_os_family|lower }}.yml"
  tags:
    - php

- name: installing PHP (FastCGI SAPI) via apt
  apt: name={{ item }} state=latest
  with_items: php_role.fpm.packages
  when: ansible_os_family == "Debian"
  tags:
    - php

- name: installing PHP (FastCGI SAPI) via yum
  yum: name={{ item }} state=latest enablerepo=remi,remi-php56
  with_items: php_role.fpm.packages
  when: ansible_os_family == "RedHat"
  tags:
    - php

- name: removing FPM configuration
  file:
    path=/etc/php5/fpm/php.ini
    state=absent
  register: php_result
  when: ansible_os_family == "Debian"
  tags:
    - nginx

- name: enabling FPM configuration
  file:
    src=/etc/php.ini
    dest=/etc/php5/fpm/php.ini
    state=link
  when: (ansible_os_family == "Debian") and (php_result|changed)
  tags:
    - nginx

- name: copying pool's configurations on Debian/Ubuntu
  template: src=pool.d/www.conf.j2 dest=/etc/php5/fpm/pool.d/{{ item.key }}.conf
  with_dict: '{{php_pool}}'
  when: ansible_os_family == "Debian"
  tags:
    - php

- name: copying pool's configurations on RHEL/CentOS
  template: src=pool.d/www.conf.j2 dest=/etc/php-fpm.d/{{ item.key }}.conf
  with_dict: '{{php_pool}}'
  when: ansible_os_family == "RedHat"
  tags:
    - php

- name: creating pool's groups
  group: name={{ item.value.group }} state=present system=yes
  when: item.value.group is defined
  with_dict: '{{php_pool}}'
  tags:
    - php

- name: creating pool's users
  user: name={{ item.value.owner }} group={{ item.value.group }} state=present system=yes
  when: (item.value.owner is defined) and (item.value.group is defined)
  with_dict: '{{php_pool}}'
  tags:
    - php

- name: creating log directories
  file:
    path={{ php_role.fpm.logdir }}/{{ item.key }}
    state=directory
    mode=0755
    owner={{ php_role.fpm.owner }}
    group={{ php_role.fpm.group }}
    recurse=yes
  with_dict: '{{stores}}'
  tags:
    - php

- name: restarting PHP-FPM
  command: service {{ php_role.fpm.service }} restart
  tags:
    - php
